use kimaster_db;

CREATE TABLE IF NOT EXISTS users (
    email VARCHAR(255) PRIMARY KEY,
    password LONGTEXT NOT NULL,
    sessionKey LONGTEXT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    lastSeenAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);